# -- Postgres
services:
  postgres:
    image: postgres:16
    container_name: biblioteca_postgres
    restart: always

    environment:
      POSTGRES_DB: biblioteca_db
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: ...

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

      # -- Oracle

  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    environment:
      ORACLE_PASSWORD: ...
      
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata


       #Scripts SQL
      - ../database/migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
  oracle-data: